import Link from "next/link";
import { Header, Footer } from "../components/SiteChrome";
import Reveal from "../components/Reveal";
import { services, testimonials, process } from "../lib/data";

const icons = ["◌", "⌁", "✦", "↗", "◈", "⊕", "⌘", "◎"];

export default function Home() {
  const jsonLd = { "@context": "https://schema.org", "@type": "ProfessionalService", name: "SellNautix", description: "Amazon growth, marketplace operations, and practical seller training.", url: "https://sellnautix.com", email: "yousuyogbhandari@gmail.com", telephone: "+919960514466", areaServed: "India", address: { "@type": "PostalAddress", addressLocality: "Pune", addressRegion: "Maharashtra", addressCountry: "IN" }, serviceType: services.map(s => s.name) };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Header /><main>
    <section className="hero" id="top"><div className="hero-grid"></div><div className="wrap hero-content"><Reveal className="hero-copy"><p className="eyebrow light">Amazon growth & marketplace operations</p><h1>See the signal.<br/><em>Own the next move.</em></h1><p className="hero-intro">SellNautix pairs Amazon expertise with an intelligent, practical operating system - so brands can make clearer decisions, execute faster, and grow with confidence.</p><div className="hero-actions"><Link href="/contact" className="button">Get a Growth Diagnostic <span>↗</span></Link><a href="#services" className="text-link light">Explore our services <span>↓</span></a></div></Reveal><Reveal className="hero-console" delay={180}><div className="console-top"><span className="pulse"></span> SELLNAUTIX / MISSION CONTROL <span>LIVE</span></div><div className="console-main"><p>Growth clarity</p><strong>01 <small>system</small></strong><div className="arc"><i></i><i></i><i></i><b></b></div><div className="console-tags"><span>Account health</span><span>Catalogue</span><span>Advertising</span><span>Conversion</span></div></div><div className="console-bottom"><div><b>Since</b><strong>2017</strong></div><div><b>Approach</b><strong>Strategy + action</strong></div></div></Reveal></div><div className="hero-rule"><div className="wrap"><span>Scroll to navigate</span><span>Amazon expertise · compliance focus · practical support</span></div></div></section>

    <section className="proof-strip"><div className="wrap proof-grid"><div><strong>8+</strong><span>Years in Amazon operations</span></div><div><strong>500+</strong><span>Sellers trained practically</span></div><div><strong>2017</strong><span>Building marketplaces better</span></div><div><strong>1:1</strong><span>Personalised consulting</span></div></div></section>

    <section className="section intro-section"><div className="wrap split"><Reveal><p className="eyebrow">Built for Amazon growth</p><h2>A clearer path to <em>better results.</em></h2></Reveal><Reveal delay={100}><p className="body-large">Amazon is a moving system of catalogue health, buyer intent, advertising performance, policy, and operations. SellNautix gives you an experienced partner to see what matters, prioritise what changes the business, and execute it hands-on.</p><Link href="/contact" className="text-link">Talk to an Amazon operator <span>↗</span></Link></Reveal></div></section>

    <section className="section dark services-section" id="services"><div className="wrap"><Reveal><p className="eyebrow light">Core offerings</p><div className="section-head"><h2>Every critical<br/><em>Amazon move.</em></h2><p>Clear scope, visible starting prices, and practical implementation. Every service is designed around a real operating problem.</p></div></Reveal><div className="service-list">{services.map((service, i) => <Reveal key={service.id} delay={i * 45}><Link className="service-row" href={`/services/${service.slug}`}><span className="service-id">{service.id.replace("SVC-", "0")}</span><span className="service-icon">{icons[i]}</span><span className="service-name">{service.name}</span><span className="service-meta"><b>{service.price}</b><small>Starting price · {service.model}</small></span><span className="service-arrow">↗</span></Link></Reveal>)}</div><Reveal><div className="service-cta"><p>Not sure where to start?</p><Link href="/contact" className="button button-inverse">Get a focused Growth Diagnostic <span>↗</span></Link></div></Reveal></div></section>

    <section className="section choose-section"><div className="wrap"><Reveal><p className="eyebrow">Why Choose SellNautix</p><div className="section-head light-head"><h2>Experienced enough<br/>to be <em>useful on day one.</em></h2><p>We bring both marketplace knowledge and the discipline to apply it to your specific account, team, and business goals.</p></div></Reveal><div className="stat-cards"><Reveal><article><span>01</span><strong>Since<br/>2017</strong><p>8+ years of Amazon marketplace experience.</p></article></Reveal><Reveal delay={80}><article><span>02</span><strong>500+<br/>sellers trained</strong><p>Practical learning for people who want to operate better.</p></article></Reveal><Reveal delay={160}><article><span>03</span><strong>Compliance-<br/>focused</strong><p>Built around sustainable growth and account health.</p></article></Reveal><Reveal delay={240}><article><span>04</span><strong>Personal,<br/>ongoing support</strong><p>Consulting that stays close to implementation.</p></article></Reveal></div><div className="choose-foot"><span>Amazon Marketplace Expertise</span><span>Practical Implementation</span><span>Personalized Consulting</span><span>Ongoing Business Support</span></div></div></section>

    <section className="section training-section" id="training"><div className="wrap"><Reveal><p className="eyebrow">Training Experience</p><div className="training-heading"><h2>Built in the marketplace.<br/><em>Shared in the classroom.</em></h2><p>SellNautix has trained 500+ Amazon sellers through practical learning sessions, and delivered guest lectures and workshops for MBA students and educational institutions on marketplace operations, eCommerce strategy, and digital business. Training uses real-world Amazon case studies, Seller Central demonstrations, and marketplace best practices.</p></div></Reveal><div className="training-grid"><Reveal className="training-photo photo-large"><img src="/training/page-4.png" alt="Suyog Bhandari delivering a guest lecture on online business opportunities"/><span>IMERT, Pune · Entrepreneurship Development Cell</span></Reveal><Reveal className="training-photo photo-small" delay={120}><img src="/training/page-3.png" alt="Amazon marketplace training session at IMERT Pune"/><span>Practical classroom session</span></Reveal><Reveal className="training-credential" delay={200}><p className="eyebrow">Institutional recognition</p><h3>Guest speaker invitation and letter of appreciation from MM&apos;s Institute of Management Education Research & Training, Pune.</h3><a href="/training/page-2.png" target="_blank" className="text-link">View appreciation letter <span>↗</span></a><div className="credential-badges"><span>500+ sellers trained</span><span>Guest lectures</span><span>Hands-on workshops</span></div></Reveal></div></div></section>

    <section className="section credential-section"><div className="wrap"><Reveal><p className="eyebrow">Credentials library</p><div className="section-head"><h2>Proof that<br/><em>travels with you.</em></h2><p>Institutional confirmation, workshop photographs, and real LinkedIn recommendations offer an evidence trail for prospective clients and institutions.</p></div></Reveal><div className="credential-grid"><Reveal><a className="credential-card image-card" href="/training/page-1.png" target="_blank"><img src="/training/page-1.png" alt="IMERT guest speaker invitation"/><span>Institutional letters</span><b>01 ↗</b></a></Reveal><Reveal delay={80}><a className="credential-card image-card" href="/training/page-7.png" target="_blank"><img src="/training/page-7.png" alt="Guest speaker workshop recognition"/><span>Workshop photographs</span><b>02 ↗</b></a></Reveal><Reveal delay={160}><a className="credential-card image-card" href="#linkedin-recommendations"><img src="/linkedin-recommendations/ajay-mehta.png" alt="LinkedIn recommendation from Ajay Mehta"/><span>LinkedIn recommendations</span><b>03 ↓</b></a></Reveal><Reveal delay={240}><article className="credential-card gst-card"><span>GSTIN</span><strong>27ANZPB2513M2ZM</strong><p>Registered business credential</p><small>SellNautix · Pune, Maharashtra</small></article></Reveal></div></div></section>

    <section className="section founder-section" id="about"><div className="wrap founder-grid"><Reveal className="founder-image"><img src="/training/page-7.png" alt="Suyog Bhandari, founder of SellNautix, at an educational workshop"/></Reveal><Reveal className="founder-copy" delay={100}><p className="eyebrow">About the founder</p><h2>Marketplace work needs a <em>real operator.</em></h2><h3>Suyog Bhandari</h3><p className="body-large">Founder of SellNautix and an Amazon marketplace consultant with 8+ years of practical experience across account operations, catalogue management, advertising, compliance, and seller training.</p><div className="founder-facts"><span>8+ years Amazon experience</span><span>500+ sellers trained</span><span>Practical, compliance-aware guidance</span></div><a className="linkedin-button" href="https://www.linkedin.com/in/suyogpbhandari" target="_blank" rel="noreferrer"><b>in</b> Connect on LinkedIn <span>↗</span></a></Reveal></div></section>

    <section className="section process-section" id="process"><div className="wrap"><Reveal><p className="eyebrow light">Our process</p><div className="section-head"><h2>Clarity becomes<br/><em>momentum.</em></h2><p>A five-step operating rhythm that turns a real Amazon challenge into sustained, accountable action.</p></div></Reveal><div className="timeline">{process.map(([number, title, text], i) => <Reveal key={number} delay={i * 70}><article><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article></Reveal>)}</div></div></section>

    <section className="section results-section" id="testimonials"><div className="wrap"><Reveal><p className="eyebrow">Client stories</p><div className="section-head"><h2>Trusted for the work<br/><em>behind the numbers.</em></h2><p>Every review below is drawn from SellNautix&apos;s LinkedIn recommendations.</p></div></Reveal><div className="testimonial-grid">{testimonials.map((t, i) => <Reveal key={t.id} delay={i * 45}><article className={i === 4 ? "testimonial featured" : "testimonial"}><div className="stars">★★★★★</div><blockquote>“{t.text}”</blockquote><div className="reviewer"><strong>{t.name}</strong><span>{t.role}</span></div></article></Reveal>)}</div><Reveal><div className="linkedin-proof" id="linkedin-recommendations"><div><p className="eyebrow">LinkedIn recommendation screenshots</p><h3>Read the original recommendations.</h3></div><a className="linkedin-button" href="https://www.linkedin.com/in/suyogpbhandari" target="_blank" rel="noreferrer"><b>in</b> View LinkedIn <span>↗</span></a><div className="linkedin-shots">{["ajay-mehta","munish-saini","hasina-shaikh","abdul-rahman","reflecto-safe"].map((name) => <a key={name} href={`/linkedin-recommendations/${name}.png`} target="_blank"><img src={`/linkedin-recommendations/${name}.png`} alt={`LinkedIn recommendation screenshot from ${name.replace('-', ' ')}`}/></a>)}</div></div></Reveal></div></section>

    <section className="cta-section"><div className="wrap"><Reveal><p className="eyebrow light">Your next move</p><h2>Let&apos;s make Amazon<br/><em>more manageable.</em></h2><p>Start with a focused conversation around your current account, catalogue, growth target, or operational challenge.</p><Link href="/contact" className="button button-inverse">Request a Growth Diagnostic <span>↗</span></Link></Reveal></div></section>
  </main><Footer /></>;
}
