export const services = [
  { id: "SVC-001", slug: "amazon-account-management", name: "Amazon Account Management", price: "₹15,000", model: "Monthly retainer", timeline: "Ongoing monthly", bestFor: "Brand owners and sellers seeking end-to-end management and consistent account growth on Amazon.", details: "Complete day-to-day management of Amazon Seller Central accounts including account health monitoring, performance metrics, inventory management, catalog maintenance, FBA operations, customer service guidance, and strategic business consulting." },
  { id: "SVC-002", slug: "amazon-listing-optimization", name: "Amazon Listing Optimization", price: "₹5,000", model: "One-time project", timeline: "1-2 weeks", bestFor: "Brands looking to increase organic ranking, click-through rates, and listing conversion rates.", details: "Optimization of product listings using Amazon SEO best practices to improve discoverability and conversions. Includes keyword research, titles, bullet points, descriptions, backend search terms, A+ content guidance, and image recommendations." },
  { id: "SVC-003", slug: "amazon-account-reinstatement-appeals", name: "Amazon Account Reinstatement & Appeals", price: "₹10,000", model: "Fixed-fee service", timeline: "3-7 days", bestFor: "Sellers facing account suspensions, ASIN suppressions, or urgent compliance notifications.", details: "Preparation of professional appeal documentation and evidence-based Plans of Action (POA) for account suspensions, ASIN reinstatements, IP complaints, restricted products, and policy violations." },
  { id: "SVC-004", slug: "amazon-advertising-ppc", name: "Amazon Advertising (PPC)", price: "₹10,000", model: "Monthly retainer", timeline: "Ongoing monthly", bestFor: "Businesses aiming to maximize ROAS, lower ACoS, and scale paid sales velocity on Amazon.", details: "Setup, management, and continuous optimization of Sponsored Products, Sponsored Brands, and Sponsored Display campaigns. Includes bid management, keyword research, search term analysis, and ad audits." },
  { id: "SVC-005", slug: "amazon-account-health-compliance", name: "Amazon Account Health & Compliance", price: "₹12,000", model: "Monthly retainer", timeline: "Ongoing monthly", bestFor: "High-volume sellers needing continuous risk mitigation to prevent account suspensions or listing blocks.", details: "Proactive account health monitoring, performance reviews, policy compliance checks, risk assessments, listing compliance audits, and actionable corrective recommendations." },
  { id: "SVC-006", slug: "product-compliance-category-approval", name: "Product Compliance & Category Approval", price: "₹10,000", model: "One-time setup", timeline: "1-2 weeks", bestFor: "Sellers expanding into ungated, restricted, or regulated categories (e.g., Health & Personal Care, Foods).", details: "Complete support for documentation required for product approvals and ungating, including category approval requests, compliance document verification, invoice reviews, and brand authorization guidance." },
  { id: "SVC-007", slug: "variation-catalog-management", name: "Variation & Catalog Management", price: "₹5,000", model: "One-time project", timeline: "3-5 days", bestFor: "Sellers with complex SKU portfolios or broken parent-child listings needing catalog cleanups.", details: "Management of complex Amazon catalog structures following policy guidelines. Includes parent-child variation creation, listing merges/splits, duplicate resolution, catalog cleanup, and flat file troubleshooting." },
  { id: "SVC-008", slug: "amazon-seller-training", name: "Amazon Seller Training", price: "₹10,000", model: "Training program + one month hands-on support", timeline: "1-3 weeks", bestFor: "Entrepreneurs, internal e-commerce teams, and businesses wanting in-house Amazon operational expertise.", details: "Practical, experience-based training covering Seller Central, product research, SEO listings, FBA, PPC, account health, policies, and Brand Registry. Delivered online or in person, in up to five hours split across multiple sessions, with 30 days of support after training." }
];

export const testimonials = [
  { id: "TST-001", name: "Ajay Mehta", role: "Founder at Maa Makhana", rating: 5, text: "Working with Suyog Bhandari and the SellNautix team has been a great experience. They guided us through setting up our brand on Amazon and explained every step clearly. They helped with category approvals, listing optimization, advertising campaigns, and understanding business reports, making it much easier to manage our seller account. Whenever we had questions, they responded promptly and provided practical solutions. Their knowledge of Amazon's processes and policies has been valuable for growing our business. I would recommend SellNautix to any brand looking for reliable Amazon account management and marketplace support." },
  { id: "TST-002", name: "Munish Saini", role: "Founder of Herbal Engine | Nutraceuticals & Wellness Industry", rating: 5, text: "Suyog Bhandari has managed our seller account exceptionally well for the past five years. He is knowledgeable, dedicated, responsive, and always provides valuable guidance. His support has been instrumental in smoothly managing and growing our account and our brand Herbal Engine." },
  { id: "TST-003", name: "Hasina Shaikh", role: "Exporter at Herbever", rating: 5, text: "We have worked with Suyog for the past five years for our brand, Herbever, on Amazon. He has helped us grow our brand significantly by managing our Seller Central account in a professional and organized manner. His expertise in resolving account health issues, policy violations, listing challenges, and other Seller Central-related problems has been extremely valuable. He has always provided timely support and practical solutions, helping us maintain a healthy account and continue growing." },
  { id: "TST-004", name: "Abdul Rahman", role: "Investment Analyst | CISI | SCA", rating: 5, text: "It was a pleasure working with Mr Suyog. Although he served as our account manager for only a brief period, he helped our company grow immensely during his tenure. Through his thorough guidance, we managed to scale significantly." },
  { id: "TST-005", name: "Reflecto Safe", role: "Digital Marketing Specialist at Reflectosafe", rating: 5, text: "Amazon Growth Success Story - ReflectoSafe: We would like to share our experience working with Suyog, who has been managing our Amazon business since January 2021. Over the course of his tenure, Suyog has demonstrated exceptional dedication, professionalism, and deep expertise in Amazon marketplace operations. He has been instrumental in handling end-to-end account management, including inventory planning, account health management, order operations, and overall business growth strategy. One of the key highlights of his contribution has been the consistent and measurable growth of our business. Under his management, our product catalogue expanded significantly from 25 SKUs to over 250 SKUs, while our monthly sales grew from approximately INR 10,000 to INR 300,000. He also successfully managed complex operational areas such as Amazon Seller Flex enrollment and operations, ensuring smooth execution and improved fulfillment efficiency. Suyog's ability to understand Amazon policies, maintain compliance, and optimize performance has played a crucial role in strengthening our brand presence and customer trust on the platform. We highly recommend Suyog to any business looking for a reliable and knowledgeable Amazon account management professional." }
];

export const process = [
  ["01", "Consultation", "We listen to your goals, constraints, catalogue, and the outcome you want Amazon to deliver."],
  ["02", "Business Assessment", "We examine account health, listings, advertising, competitors, and the operational blockers holding growth back."],
  ["03", "Strategy Development", "You receive a prioritised roadmap built around profit, compliance, conversion, and practical next moves."],
  ["04", "Implementation", "Our team moves from plan to action across Seller Central, advertising, catalogue, and content."],
  ["05", "Continuous Support", "We review performance, resolve issues, and keep adapting as your Amazon business evolves."]
];

export const serviceDetails = {
  "SVC-001": { offerings: ["Account Health monitoring", "Performance metrics management", "Order management", "Inventory planning", "FBA operations", "Business reports", "Policy compliance", "Operational consulting"], benefits: ["A more organised day-to-day Seller Central operation", "Early visibility into account-health and performance risks", "Better inventory and catalogue coordination", "More time to focus on products and customers"] },
  "SVC-002": { offerings: ["Keyword research", "Amazon SEO optimization", "Product titles", "Bullet points", "Product descriptions", "Backend search terms", "A+ Content guidance", "Catalog optimization", "Image recommendations"], benefits: ["Improved discoverability for relevant buyer searches", "Clearer product communication that supports conversion", "A structured content foundation for organic growth", "Better alignment between listings, ads, and customer intent"] },
  "SVC-003": { offerings: ["Account suspensions", "ASIN reinstatement", "Intellectual Property complaints", "Restricted product issues", "Product authenticity documentation", "Performance notifications", "Policy consultation", "Plan of Action preparation"], benefits: ["A root-cause-first response rather than a generic appeal", "Evidence-based documentation prepared around the issue", "Practical preventive measures aligned to Amazon policy", "Support when an account or listing problem needs urgent attention"] },
  "SVC-004": { offerings: ["Sponsored Products", "Sponsored Brands", "Sponsored Display", "Campaign optimization", "Bid management", "Keyword research", "Search term analysis", "Advertising audits", "Performance reporting"], benefits: ["Greater visibility across relevant Amazon search terms", "More informed bid and budget decisions", "A clearer view of advertising performance", "Continuous optimization to support paid-sales velocity"] },
  "SVC-005": { offerings: ["Account Health monitoring", "Performance review", "Policy compliance", "Risk assessment", "Listing compliance", "Corrective recommendations"], benefits: ["Proactive identification of compliance and account-health risks", "A more reliable operating rhythm for high-volume accounts", "Clear corrective recommendations before issues escalate", "Greater confidence in policy-sensitive decisions"] },
  "SVC-006": { offerings: ["Category approval requests", "Product compliance documentation", "Invoice review", "Brand authorization guidance", "Supporting documentation review", "Restricted category assistance"], benefits: ["More organised preparation for approval submissions", "Support navigating restricted and regulated categories", "Reduced guesswork around document requirements", "A clearer path to compliant catalogue expansion"] },
  "SVC-007": { offerings: ["Parent-child variations", "Listing merges", "Listing splits", "Duplicate listing resolution", "Catalog cleanup", "Flat file support"], benefits: ["A cleaner, more navigable catalogue structure", "Support for complex SKU families and variation relationships", "Reduced confusion caused by duplicate or broken listings", "Policy-aware changes to catalogue relationships"] },
  "SVC-008": { offerings: ["Amazon Seller Central", "Product research", "Product listings", "Amazon SEO", "FBA", "PPC", "Account Health", "Amazon policies", "Compliance", "Product approvals", "Brand Registry", "Business growth"], benefits: ["Practical skills rooted in marketplace experience", "Online or in-person delivery for individuals, teams, and institutions", "Real-world case studies and Seller Central demonstrations", "30 days of hands-on support after training"] }
};
